### PR TITLE
Issue 117 fix end game screen

### LINKED ISSUE #117: Fix end game screen
Let the player leave the game once it's finished. Deal with:
- lingering Exit label + button
- persistent message displayed
- elements not cleared for message
- impossible to tap Menu

### PR DESCRIPTION
**Pull request by adrian-golian**
Closes #117 
Depends on #121 - RESOLVE IT FIRST

### CODE REVIEW

File: Blef/GameScene.swift [hunk 1]
```diff
@@ -326,44 +323,41 @@ class GameScene: SKScene, GameManagerDelegate, UIPickerViewDelegate, UIPickerVie
     }
     
     func touchUp(atPoint pos : CGPoint) {
+        if self.isDisplayingMessage {
+            clearMessage()
+            isBetScrolling = false
+            return
+        }
```
Comment (maciej-pomykala) [inline Blef/GameScene.swift:330]: Instead of calling moveToStartScene inside of this, we could have another if statement above that deals with the case of the game being finished

**Review by maciej-pomykala — CHANGES_REQUESTED** [review]

**Comment by adrian-golian** [comment]
(Just rebased onto `develop`)

**Review by maciej-pomykala — APPROVED** [review]
